name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reason:
        description: Reason for manual run.
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo Hello, world!
          echo "run reason: ${{ inputs.reason }}"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
